<?php

declare(strict_types=1);

namespace App\Data\Reminders;

/**
 * Proof that a worker holds the CURRENT claim on a reminder.
 *
 * The token is generated by the server at claim time and is new on every claim.
 * A worker carries it from the claim to the dispatch, and may act only while
 * the stored token still equals the one it carries — so a worker whose claim
 * was swept and replaced while it stalled holds an identity nobody recognises
 * any more, and is structurally unable to send.
 *
 * Ownership is never inferred from `status`, and never from comparing
 * timestamps: those answer "is someone working on this" and "when", not "is it
 * still ME".
 */
final readonly class ReminderClaim
{
    public function __construct(
        public int $reminderId,
        public string $token,
    ) {}
}
