<?php

declare(strict_types=1);

use App\Enums\ToolInvocationStatus;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Phase F2 — the CURRENT projection of every tool invocation.
 *
 * The identity of an invocation is `idempotency_key`, generated by the server
 * from persisted facts (`msg:<id>:tool:<key>@<v>:call:<n>`) and never by a
 * model, a provider or a caller. Its UNIQUE index is the race arbiter: the
 * first writer creates the row, every later writer with the same key observes
 * it instead — replaying its recorded result, reporting it as in flight, or
 * reporting a CONFLICT when the canonical input hash differs.
 *
 * The row snapshots `tool_key` + `tool_version` (and, for readability, the
 * capability and side-effect class of that version). Because a shipped tool
 * version is immutable, every policy of that version — its timeout above all —
 * stays deterministically recoverable from the registry, so no policy is
 * duplicated into this table: what is stored here is what actually HAPPENED
 * (when it started, when it finished, how long it took, how it ended).
 *
 * No personal data: the input is the tool's own bounded, schema-validated
 * arguments, and everything else is an id, a code or a hash.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('tool_invocations', function (Blueprint $table) {
            $table->id();
            $table->foreignId('subscriber_id')->constrained('users')->cascadeOnDelete();

            // The exact contract this invocation was claimed against.
            $table->string('tool_key', 64);
            $table->unsignedSmallInteger('tool_version');
            $table->string('capability', 64);
            $table->string('side_effect', 16);

            // Identity and input.
            $table->string('idempotency_key', 191);
            $table->char('input_hash', 64);
            $table->json('input');

            $table->string('status', 16);

            // Where the identity came from. Nullable so deleting a message or a
            // conversation never destroys invocation history; the orchestration
            // that derives a key always has both.
            $table->foreignId('message_id')->nullable()->constrained('messages')->nullOnDelete();
            $table->foreignId('conversation_id')->nullable()->constrained('conversations')->nullOnDelete();
            $table->unsignedSmallInteger('call_index');

            // What happened.
            $table->json('output')->nullable();
            $table->string('failure_kind', 32)->nullable();
            $table->string('refusal_reason', 32)->nullable();
            $table->unsignedInteger('duration_ms')->nullable();
            $table->timestamp('started_at')->nullable();
            $table->timestamp('finished_at')->nullable();

            // The concurrency contract AND the number of persisted transitions.
            $table->unsignedInteger('version')->default(1);
            $table->timestamps();

            $table->unique('idempotency_key', 'tool_invocations_idempotency_key_unique');
            // A subscriber's invocation history, newest first.
            $table->index(['subscriber_id', 'created_at'], 'tool_invocations_subscriber_created_idx');
            // The stale-running sweep, and any operational read by state.
            $table->index(['status', 'created_at'], 'tool_invocations_status_created_idx');
        });

        if (DB::getDriverName() === 'pgsql') {
            $states = "'".implode("', '", ToolInvocationStatus::values())."'";

            // The lifecycle is a code table; these constraints keep the ROW
            // coherent whatever writes it.
            DB::statement("ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_status_check CHECK (status IN ({$states}))");
            DB::statement('ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_version_check CHECK (version >= 1)');
            DB::statement('ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_call_index_check CHECK (call_index >= 1)');
            DB::statement("ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_output_check CHECK (output IS NULL OR status = 'succeeded')");
            DB::statement("ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_succeeded_check CHECK (status <> 'succeeded' OR (output IS NOT NULL AND started_at IS NOT NULL AND finished_at IS NOT NULL))");
            DB::statement("ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_failed_check CHECK (status NOT IN ('failed', 'timed_out') OR (failure_kind IS NOT NULL AND started_at IS NOT NULL AND finished_at IS NOT NULL))");
            // A refusal happens BEFORE anything runs: never started, no output, no usage.
            DB::statement("ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_refused_check CHECK (status <> 'refused' OR (refusal_reason IS NOT NULL AND started_at IS NULL AND output IS NULL))");
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('tool_invocations');
    }
};
