<?php

declare(strict_types=1);

use App\Enums\ToolInvocationStatus;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Phase F2 — the CURRENT projection of every tool invocation.
 *
 * The identity of an invocation is `idempotency_key`, generated by the server
 * from persisted facts (`msg:<id>:tool:<key>@<v>:call:<n>`) and never by a
 * model, a provider or a caller. Its UNIQUE index is the race arbiter: the
 * first writer creates the row, every later writer with the same key observes
 * it instead — replaying its recorded result, reporting it as in flight, or
 * reporting a CONFLICT when the canonical input hash differs.
 *
 * The identity is the SERVER-OWNED CALL SLOT, not the tool: one message and one
 * call index is one invocation, whatever tool the model proposed for it. The
 * claim facts (`tool_key`, `tool_version`, `input_hash`) are stored ON the slot,
 * so proposing a different tool, a different version or a different input at a
 * slot that already exists is a CONFLICT — never a second row for the same
 * logical call. `UNIQUE(message_id, call_index)` is the database's own statement
 * of that rule, alongside the unique identity string.
 *
 * The row snapshots `tool_key` + `tool_version` (and, for readability, the
 * capability and side-effect class of that version). Because a shipped tool
 * version is immutable, every policy of that version — its timeout above all —
 * stays deterministically recoverable from the registry, so no policy is
 * duplicated into this table: what is stored here is what actually HAPPENED
 * (when it started, when it finished, how long it took, how it ended).
 *
 * NO RAW TOOL ARGUMENTS. A validated argument is not a safe argument:
 * `memory.read@1.query` is subscriber-authored text and may legally contain a
 * name, a phone number, an email or a private sentence. F2 never retries a read
 * after a crash, so it needs no raw input to recover: the canonical value lives
 * only in memory for the duration of the call, and what is persisted is the
 * `input_hash` plus safe structural metadata (`input_fields`) and whatever a
 * per-field policy explicitly marks persistable (`ToolInputPersistence`, empty
 * for every tool shipped so far).
 *
 * DURABLE HISTORY. `subscriber_id` is a historical reference WITHOUT a foreign
 * key — the same pattern `customer_payments`, `subscription_events` and
 * `usage_events` already use: deleting the account cascades the live rows away,
 * it never erases the execution history that `usage_events.tool_invocation_ref`
 * points at. `message_id` / `conversation_id` are live links that null out.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('tool_invocations', function (Blueprint $table) {
            $table->id();
            // Immutable attribution snapshot, deliberately NOT a foreign key:
            // the history outlives the account (see the class docblock).
            $table->unsignedBigInteger('subscriber_id');

            // The exact contract this invocation was claimed against.
            $table->string('tool_key', 64);
            $table->unsignedSmallInteger('tool_version');
            $table->string('capability', 64);
            $table->string('side_effect', 16);

            // Identity and input.
            $table->string('idempotency_key', 191);
            $table->char('input_hash', 64);
            // The persistable subset of the canonical input — empty for every
            // tool shipped so far — plus the names (never the values) of the
            // declared fields the call actually carried.
            $table->json('input');
            $table->json('input_fields');

            $table->string('status', 16);

            // Where the identity came from. Nullable so deleting a message or a
            // conversation never destroys invocation history; the orchestration
            // that derives a key always has both.
            $table->foreignId('message_id')->nullable()->constrained('messages')->nullOnDelete();
            $table->foreignId('conversation_id')->nullable()->constrained('conversations')->nullOnDelete();
            $table->unsignedSmallInteger('call_index');

            // What happened.
            $table->json('output')->nullable();
            $table->string('failure_kind', 32)->nullable();
            $table->string('refusal_reason', 32)->nullable();
            $table->unsignedInteger('duration_ms')->nullable();
            $table->timestamp('started_at')->nullable();
            $table->timestamp('finished_at')->nullable();

            // The concurrency contract AND the number of persisted transitions.
            $table->unsignedInteger('version')->default(1);
            $table->timestamps();

            $table->unique('idempotency_key', 'tool_invocations_idempotency_key_unique');
            // The call slot itself, as a database integrity rule: one message
            // and one call index can hold exactly one invocation.
            $table->unique(['message_id', 'call_index'], 'tool_invocations_message_call_unique');
            // A subscriber's invocation history, newest first.
            $table->index(['subscriber_id', 'created_at'], 'tool_invocations_subscriber_created_idx');
            // The stale-running sweep, and any operational read by state.
            $table->index(['status', 'created_at'], 'tool_invocations_status_created_idx');
        });

        if (DB::getDriverName() === 'pgsql') {
            $states = "'".implode("', '", ToolInvocationStatus::values())."'";

            // The lifecycle is a code table; these constraints keep the ROW
            // coherent whatever writes it.
            DB::statement("ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_status_check CHECK (status IN ({$states}))");
            DB::statement('ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_version_check CHECK (version >= 1)');
            DB::statement('ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_call_index_check CHECK (call_index >= 1)');
            DB::statement("ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_output_check CHECK (output IS NULL OR status = 'succeeded')");
            DB::statement("ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_succeeded_check CHECK (status <> 'succeeded' OR (output IS NOT NULL AND started_at IS NOT NULL AND finished_at IS NOT NULL))");
            DB::statement("ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_failed_check CHECK (status NOT IN ('failed', 'timed_out') OR (failure_kind IS NOT NULL AND started_at IS NOT NULL AND finished_at IS NOT NULL))");
            // A refusal happens BEFORE anything runs: never started, no output, no usage.
            DB::statement("ALTER TABLE tool_invocations ADD CONSTRAINT tool_invocations_refused_check CHECK (status <> 'refused' OR (refusal_reason IS NOT NULL AND started_at IS NULL AND output IS NULL))");
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('tool_invocations');
    }
};
