<?php

declare(strict_types=1);

namespace App\Data\Voice;

/**
 * Exclusive ownership of one voice note, for the length of one attempt.
 *
 * The TOKEN is the whole value. It is generated by the server, written under a
 * row lock, and compared with `hash_equals` before anything irreversible — so a
 * worker that was swept and superseded discovers it no longer owns this voice
 * note BEFORE it increments the attempt counter and BEFORE it reaches the
 * provider. A queue lock cannot do that job: it expires with the worker, and
 * the thing being protected here is money already spent.
 *
 * Claiming and working are deliberately two steps, exactly as reminder delivery
 * separates them. Keeping them apart is what lets a test hold a claim, age it,
 * let another process take it, and then prove the first process is refused.
 */
final readonly class VoiceClaim
{
    public function __construct(
        public int $messageId,
        public string $token,
    ) {}
}
